# Generated by Django 3.0.8 on 2020-09-24 07:56

import core.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(max_length=100)),
                ('address_street2', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_zip', models.CharField(max_length=100)),
                ('address_country', models.CharField(max_length=100)),
                ('address_country_code', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('address_state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'core_address_validate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('weight_value', models.CharField(max_length=100)),
                ('weight_unit', models.CharField(max_length=100)),
                ('dimensions_length', models.CharField(max_length=100)),
                ('dimensions_width', models.CharField(max_length=100)),
                ('dimensions_depth', models.CharField(max_length=100)),
                ('dimensions_unit', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('imgformat_layout', models.CharField(max_length=100)),
                ('imgformat_type', models.CharField(max_length=100)),
                ('imgformat_labelreturn', models.CharField(max_length=100)),
                ('is_return', models.BooleanField()),
                ('provider', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'core_packages',
                'ordering': ['order'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShippingRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=core.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UploadPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=core.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SquareCustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_square_customer',
            },
        ),
        migrations.CreateModel(
            name='SquareCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SquareCustomerInfo')),
            ],
            options={
                'db_table': 'core_square_card',
            },
        ),
        migrations.CreateModel(
            name='SellerAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vsaccount_id', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_seller_account',
            },
        ),
        migrations.CreateModel(
            name='PrepayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('prev_balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_prepay_history',
            },
        ),
        migrations.CreateModel(
            name='PrepayAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_prepay_account',
            },
        ),
        migrations.CreateModel(
            name='LabelsPrinted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.CharField(max_length=100)),
                ('clientrequest_id', models.CharField(max_length=100)),
                ('trackinginfo_number', models.CharField(max_length=100)),
                ('trackinginfo_carriername', models.CharField(max_length=100)),
                ('labeldata_type', models.CharField(max_length=100)),
                ('labeldata_content', models.CharField(max_length=100)),
                ('success', models.BooleanField()),
                ('code', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_labels_printed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_unique_id', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_company', models.CharField(max_length=100)),
                ('sender_zip', models.CharField(max_length=100)),
                ('sender_city', models.CharField(max_length=100)),
                ('sender_state', models.CharField(max_length=100)),
                ('sender_phone', models.CharField(max_length=100)),
                ('sender_email', models.CharField(max_length=100)),
                ('sender_country', models.CharField(max_length=100)),
                ('sender_country_code', models.CharField(max_length=100)),
                ('sender_address1', models.CharField(max_length=100)),
                ('sender_address2', models.CharField(max_length=100)),
                ('sender_address3', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_company', models.CharField(max_length=100)),
                ('receiver_zip', models.CharField(max_length=100)),
                ('receiver_city', models.CharField(max_length=100)),
                ('receiver_state', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=100)),
                ('receiver_email', models.CharField(max_length=100)),
                ('receiver_country', models.CharField(max_length=100)),
                ('receiver_country_code', models.CharField(max_length=100)),
                ('receiver_address1', models.CharField(max_length=100)),
                ('receiver_address2', models.CharField(max_length=100)),
                ('receiver_address3', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('packages', models.ManyToManyField(to='core.Packages')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_labels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_addressbook',
                'managed': True,
            },
        ),
    ]
