# Generated by Django 3.1.2 on 2020-10-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201003_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='create_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Failed', 'Failed'), ('Created', 'Created')], default='Processing', max_length=100),
        ),
    ]
