# Generated by Django 3.1.2 on 2020-10-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_labels_create_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_unique_id', models.CharField(max_length=100)),
                ('create_status', models.CharField(choices=[('Processing', 'Processing'), ('Failed', 'Failed'), ('Created', 'Created')], default='Processing', max_length=100)),
                ('response_data', models.JSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='labels',
            name='create_status',
        ),
    ]
