# Generated by Django 3.1.2 on 2020-10-16 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20201017_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('customs_name', models.CharField(max_length=100)),
                ('customs_sku', models.CharField(max_length=100)),
                ('customs_description', models.CharField(max_length=100)),
                ('customs_quantity', models.CharField(max_length=100)),
                ('customs_acount', models.CharField(max_length=100)),
                ('customs_currency', models.CharField(max_length=100)),
                ('customs_country', models.CharField(max_length=100)),
                ('tariff_code', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_customs',
                'ordering': ['order'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='custom_items',
            field=models.ManyToManyField(to='core.Customs'),
        ),
    ]
