# Generated by Django 3.1.2 on 2020-10-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201017_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customs',
            old_name='customs_acount',
            new_name='customs_amount',
        ),
    ]
