# Generated by Django 3.1.2 on 2020-10-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201019_0733'),
        ('core', '0005_auto_20201017_0259'),
    ]

    operations = [
    ]
